server:
  port: 8080
  servlet:
    context-path: /

spring:
  application:
    name: tologram
  
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb+srv://varunbali47:R06aPI9Nasa5X3nx@cluster0.62phxrw.mongodb.net/tologram?retryWrites=true&w=majority&appName=Cluster0}
      
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      
  jackson:
    serialization:
      write-dates-as-timestamps: false
    time-zone: UTC

  # Session Configuration
  session:
    mongodb:
      collection-name: sessions
    timeout: 86400 # 24 hours in seconds

# File Upload Configuration
file:
  upload:
    dir: ${UPLOAD_DIR:./uploads}
    max-size: 10485760 # 10MB

# Logging Configuration
logging:
  level:
    com.tologram: DEBUG
    org.springframework.security: DEBUG
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
    
# Management endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized

# CORS Configuration
cors:
  allowed-origins: ${CORS_ORIGINS:http://localhost:3000,http://localhost:5173}
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: "*"
  allow-credentials: true
  max-age: 3600