spring:
  data:
    mongodb:
      uri: mongodb+srv://varunbali47:R06aPI9Nasa5X3nx@cluster0.62phxrw.mongodb.net/tologram?retryWrites=true&w=majority&appName=Cluster0

# Production JWT Configuration
jwt:
  secret: ${JWT_SECRET:myProductionSecretKey}
  expiration: 86400000 # 24 hours

# Production logging
logging:
  level:
    com.tologram: INFO
    root: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

# File upload for production
file:
  upload:
    dir: ${UPLOAD_DIR:/app/uploads}